language: node_js

node_js:
    - "8.10.0"

before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.17.3

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn run prettier-check
  - yarn run lint-check
